### ISSUE TITLE
[Feature Request] Expanding Quest suggestion

### ISSUE THREAD

**Issue by Iks4** [red2blue/AQM2#157]
**Is your feature request related to adding/removing a mod or is it a ingame suggestion.**
Essentially just pushing a few starter quests to point players in the right direction.

**Why do we need this feature?**
I've invited a few friends to play on a private server, and each of them had the same issue. They were lost on what to do. A lot of tools are here, but the info isn't.

Golems, for example, require going to the mod's wiki to lookup what each golem actually does. 

It'd be impossible to stumble on Overlord's info. None of our group even found this randomly until I scoured through the mod list. 

Knowing you can permanently lose your companion bat(and this can be avoided with etheric) lead to a lot of frustration among half of our players.

**Additional context**
I'm not big on just giving issues and not doing anything about it, however I'm also not very good at coming up with fair rewards or writing interesting text. I tried to make a few quests for our crew and they seemed to enjoy it, so I figured I'd share it here. I added a few new chapters and changed the text on golems to further explain them. Our server is on 2.0.4.1, so if there are any updates after that I don't have them. I also made a shop to save some frustration, but on a server this would cause problems. 

-Issues with my list:
There's a (albeit expensive) way to get creative flight in the end of the flight tab.
The shop tab would be horribly unbalanced w/ automatic xp farms. I'd suggest scrapping that, if you do use it.
I had fun with the QOL Quest section, but it has a somewhat dark joke.
The space tab is very poorly made entirely. Little to no dialogue, I had no idea what to do for rewards. 
Capture Souls in "Gotta catch 'em all" ended up very long. Since this doesn't have an in-game book, I put a lot of info here.

I don't mind if none of this gets used or all of this gets used. I simply wanted to share what I did for our group to alleviate their frustrations. It's my first time sharing this, so I hope I did that right?

[quests.zip](https://github.com/itsdinkd/AQM2/files/8164304/quests.zip) (/Config/FTBQuests)

**Comment by itsdinkd** [comment]
Quests are being worked on. There are over 340 mods, and 1 person, and sometimes myself working on quests. We won't be able to get them all. The quest line for golemancy was created when the mod first came out a couple months back, it changes drastically after every update it releases, but it will be addressed later. 

 The start here section is a good starting point, especially the gobber quest that is 3x the size of the others, though you won't see this due to being on a older version.

Remember this is a kitchen sink pack, there isn't a dedicated direction since there's a bit of everything. That's the beauty of it. The player picks their route. Knowing this, we still are creating quests to introduce how to use certain mods. One main thing above everything else that needs to be added is end game content. 

On a final note, I recommend you update. We've added and fixed lots of quests since 2.0.4.1

**Comment by itsdinkd** [comment]
I will check out your attachment when I get some time.  A good way to introduce stuff like this is by making a pull request into this github repo, that way we can easily review and even pull your changes into the project. Thanks!

**Comment by busterbrown1999** [comment]
Golems have also been updated in an unreleased version to better explain what each one does.

**Comment by busterbrown1999** [comment]
If you are familiar with github and you think a quest change/addition is valuable. Feel free to submit the change to the aqm2 repo and we can look over it and it could potentially end up being accepted. Try and keep the changes in smaller pull requests if you do and be descriptive of what has changed. 

I have considered adding a shop later once I get some more quests added, also have been thinking about how to keep it balanced. 

Thanks for the feedback!
